Assignment 2

PART 2


In [1]:
import numpy as np
import vugrad as vg
import matplotlib.pyplot as plt

In [9]:
x = vg.TensorNode(np.random.randn(2, 2))

a = vg.TensorNode(np.random.randn(2, 2))
b = vg.TensorNode(np.random.randn(2, 2))

c = a + b

print(c.value,"value")
print(c.source,"c.source")
print(c.source.inputs[0].value,"[0] value")
print(a.grad, "grad")

[[-0.57691621 -2.69077316]
 [ 1.4389507   2.06005097]] value
<vugrad.core.OpNode object at 0x1243c36a0> c.source
[[-0.60354064 -0.03524341]
 [ 0.54082582  1.09016263]] [0] value
[[0. 0.]
 [0. 0.]] grad
